CS460/HW8/HW8/Models/PagingInfo.cs
// PagingInfo class as found in : PRO ASP.NET MVC 5, BY	ADAM FREEMAN
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HW8.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

CS460/HW8/HW8/Models/PirateListViewModel.cs
// View Model for paging as found in : PRO ASP.NET MVC 5, BY ADAM FREEMAN
using System.Collections.Generic;

namespace HW8.Models
{
    public class PirateListViewModel
    {
        public IEnumerable<Pirate> Pirates { get; set; }
        public PagingInfo PagingInfo { get; set; }

    }
}

CS460/HW8/HW8/Controllers/AJAXController.cs
using HW8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW8.Controllers
{
    public class AJAXController : Controller
    {
        //AJAX - GET
        /// <summary>
        /// For the AJAX call that retrieves a list of booty
        /// </summary>
        /// <returns> PirateName/Booty sum list.</returns>
        public JsonResult BootyTotals()
        {
            PirateContext db = new PirateContext();
            var totals = db.Crews.GroupBy(c => c.Pirate.PirateName).Select(p => new
            {
                name = p.FirstOrDefault().Pirate.PirateName,
                Booty = p.Select(b => b.BootyValue).Sum()
            }).OrderByDescending(cb => cb.Booty).ToList();

            return Json(totals, JsonRequestBehavior.AllowGet);
        }
    }
}

CS460/HW8/HW8/Controllers/CrewController.cs
using HW8.Models;
using System.Linq;
using System.Web.Mvc;

namespace HW8.Controllers
{
    public class CrewController : Controller
    {
        private PirateContext db = new PirateContext();

        // GET: Booty
        public ActionResult Booty()
        {
            return View();
        }

        // GET: Crew
        public ActionResult Crews()
        {
            var deckHands = db.Crews.OrderBy(p => p.ShipID).ToList();
            return View(deckHands);
        }
    }
}

CS460/HW8/HW8/Controllers/PirateController.cs
using HW8.Models;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HW8.Controllers
{
    public class PirateController : Controller
    {
        private PirateContext db = new PirateContext();
        public int PageSize = 3;

        // GET: Pirate
        public ActionResult Pirates(int page = 1)
        {
            PirateListViewModel model = new PirateListViewModel
            {
                Pirates = db.Pirates.OrderByDescending(p => p.PirateName).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = db.Pirates.Count()
                }
            };
            return View(model);
        }

        // GET: Pirate/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
           
            return View(pirate);
        }

        // GET: Pirate/Create
        public ActionResult Create()
        {
            Pirate rookie = new Pirate();
            rookie.ShanghaiDate = DateTime.Now;
            return View(rookie);
        }

        // POST: Pirate/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PirateID,PirateName,ShanghaiDate,Crews")] Pirate pirateInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pirateInfo).State = EntityState.Added;
                db.SaveChanges();
                return RedirectToAction("Pirates");
            }
            return View(pirateInfo);
        }

        // GET: Pirate/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
            return View(pirate);
        }

        // POST: Pirate/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include ="PirateID,PirateName,ShanghaiDate,Crews")] Pirate pirateInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pirateInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Pirates");
            }
            return View(pirateInfo);
        }

        // GET: Pirate/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pirate = db.Pirates.Find(id);
            if (pirate == null)
            {
                return HttpNotFound();
            }
            return View(pirate);
        }

        // POST: Pirate/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Pirate pirate = db.Pirates.Find(id);
            db.Pirates.Remove(pirate);
            db.SaveChanges();
            return RedirectToAction("Pirates");
        }
    }
}

CS460/HW8/HW8/Controllers/ShipController.cs
using HW8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW8.Controllers
{
    public class ShipController : Controller
    {
        private PirateContext db = new PirateContext();

        // GET: Ship
        public ActionResult Ships()
        {
            var crewBuckets = db.Ships.OrderBy(s => s.Tonnage);
            return View(crewBuckets);
        }
    }
}

CS460/HW8/HW8/Views/Crew/Booty.cshtml
@{
    ViewBag.Title = "Booty";
}

<div class="row"><div class="col-md-10 text-center"><h1>Booty Totals</h1></div></div>
<hr />
<div id="tableStart"></div>

@section PageScripts
{
    <link href="~/Content/Booty.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Scripts/Booty.js"></script>
}

CS460/HW8/HW8/Views/Crew/Crews.cshtml
@model IEnumerable<HW8.Models.Crew>

@{
    ViewBag.Title = "Crew";
}

<h2>Crew</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pirate.PirateName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ship.ShipName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BootyValue)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Pirate.PirateName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ship.ShipName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BootyValue)
        </td>
    </tr>
}

</table>

CS460/HW8/HW8/Views/Pirate/Create.cshtml
@model HW8.Models.Pirate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pirate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PirateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PirateName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PirateName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShanghaiDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShanghaiDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShanghaiDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Roster", "Pirates")
</div>

CS460/HW8/HW8/Views/Pirate/Delete.cshtml
@model HW8.Models.Pirate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pirate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PirateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PirateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShanghaiDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShanghaiDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Roster", "Pirates")
        </div>
    }
</div>

CS460/HW8/HW8/Views/Pirate/Details.cshtml
@model HW8.Models.Pirate

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pirate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PirateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PirateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShanghaiDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShanghaiDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Crews.First().BootyValue)
        </dt>

        <dd>
            @Model.Crews.Select(c => c.BootyValue).Sum()
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PirateID }) |
    @Html.ActionLink("Back to Roster", "Pirates")
</p>

CS460/HW8/HW8/Views/Pirate/Edit.cshtml
@model HW8.Models.Pirate

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pirate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PirateID)

        <div class="form-group">
            @Html.LabelFor(model => model.PirateName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PirateName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PirateName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShanghaiDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShanghaiDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShanghaiDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Roster", "Pirates")
</div>

CS460/HW8/HW8/Views/Pirate/Pirates.cshtml
@model HW8.Models.PirateListViewModel

@{
    ViewBag.Title = "Pirates";
}


<h2>Pirates</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Pirate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pirates.FirstOrDefault().PirateName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pirates.FirstOrDefault().ShanghaiDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Pirates) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PirateName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShanghaiDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PirateID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PirateID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PirateID })
        </td>
    </tr>
}

</table>

<div>
    @using HW8.Helpers 
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Pirates", new { page = x }))
</div>